server:
  port: 8081
spring:
  security:
    user:
      name: admin
      password: admin
      roles:
        - ADMIN
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: user
    password: password
    url: jdbc:mysql://localhost:3306/resourcemanager-db
    hikari:
      poolName: Hikari
      auto-commit: true
      driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    enabled: false
