spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: user
    password: password
    url: jdbc:mysql://localhost:3306/resourcemanager-db
    hikari:
      poolName: Hikari
      auto-commit: true
      driver-class-name: com.mysql.cj.jdbc.Driver
