resource:
  jwt-key: ${JWT_KEY}
  firebase-admin-key: ${FIREBASE_ADMIN_KEY}
  cors:
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: "Authorization,X-Total-Count,Link,ETag"
    allow-credentials: true
    max-age: 1800
firebase:
  bucket-name: resource-manager-bucket
  project-id: resourcemanager-2a15b
server:
  port: 8081
spring:
  profiles:
    active: @active.profile@
  application:
    name: ResourceManager
  security:
    user:
      name: admin
      password: admin
      roles:
        - ADMIN
  jpa:
    open-in-view: true
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  liquibase:
    enabled: false
